### ISSUE TITLE
Build fails on JRuby

### ISSUE THREAD

**Issue by route** [rubycdp/ferrum#15]
Sometimes it passes without issues like here https://travis-ci.org/route/ferrum/builds/587362556
but more often it fails sporadically at any given time https://travis-ci.org/route/ferrum/jobs/585764841 with timeout.

We use concurrent-ruby primitives here like `Hash`, `Ivar`, `Mvar` and some Ruby threads for `websocket/driver` nothing unusual but I cannot spot the issue...

/cc @headius

**Comment by headius** [comment]
Hello, thanks for letting me know about this issue!

The failure is a bit confusing... the spec that fails is "Ferrum::Browser lists the open windows" but it appears that the failure happens downstream from a `browser.reset` call. The only such call I can see in `browser_spec.rb` is in a different spec, "Ferrum::Browser clears local storage after reset".

I think the failure is happening in the "before" section here: https://github.com/route/ferrum/blob/master/spec/spec_helper.rb#L55-L59

In that code, I notice a timeout of 5 seconds. If this timeout involves starting a subprocess JRuby instance, there's a chance that slower environments may not start up fast enough. If that's the problem here, then bumping to a larger timeout like 10 seconds should make this more reliable.

**Comment by route** [comment]
Thank you Charles for taking a look I'll try to investigate it further

**Comment by route** [comment]
Related to https://github.com/rubycdp/ferrum/issues/75

**Comment by route** [comment]
I don't think I have expertise and time to support JRuby

**Comment by headius** [comment]
Hey there, this fell off my radar years ago after I commented. I'd like to help!

**Comment by headius** [comment]
I did a local run and it appears to do well for a while, then something times out and everything fails after that. It looks like the Puma server is in "reset" method, so perhaps something tries to restart the server but fails, and from then on it's unavailable?

I'm happy to help get things green if you can explain how the tests work and we can collab to figure out why it starts failing. It seems to do well until it doesn't!

**Comment by headius** [comment]
There's lots of this warning too, which makes the test output pretty noisy:

```
/Users/headius/work/jruby/lib/ruby/gems/shared/gems/sinatra-3.2.0/lib/sinatra/base.rb:1140: warning: URI::RFC3986_PARSER.unescape is obsolete. Use URI::RFC2396_PARSER.unescape explicitly.
```

**Comment by headius** [comment]
It does slow down a bit when it starts failing, but it does not appear to time out completely! Here's the results I got on my local run:

```
Finished in 12 minutes 39 seconds (files took 5.48 seconds to load)
505 examples, 108 failures, 42 pending
```

Passing 80% of examples is good, right? 😀

Nearly all of the failures are this:

```
 81) Ferrum::Page::Screenshot#screenshot when encoding is base64 with jpeg supports screenshotting just the selected element
      Failure/Error: raise NoSuchTargetError unless resolved
      
      Ferrum::NoSuchTargetError:
        Ferrum::NoSuchTargetError
      Shared Example Group: "screenshot screen" called from ./spec/page/screenshot_spec.rb:321
      # ./lib/ferrum/context.rb:54:in 'create_target'
      # ./lib/ferrum/context.rb:20:in 'default_target'
      # ./lib/ferrum/context.rb:24:in 'page'
      # ./spec/page/screenshot_spec.rb:38:in 'block in <main>'
```

It seems like something fails and is not recovered, and then it starts failing all of these specs because of that. Any thoughts on where to look?

**Comment by route** [comment]
That’s a very good news for Ferrum! Basically what we do is we have simple Sinatra application, puma to serve it and then we test ferrum that it drives chrome correctly by using CDP protocol.

**Comment by route** [comment]
> There's lots of this warning too, which makes the test output pretty noisy:
> 
> ```
> /Users/headius/work/jruby/lib/ruby/gems/shared/gems/sinatra-3.2.0/lib/sinatra/base.rb:1140: warning: URI::RFC3986_PARSER.unescape is obsolete. Use URI::RFC2396_PARSER.unescape explicitly.
> ```

Unfortunately it’s in Sinatra

**Comment by route** [comment]
> It does slow down a bit when it starts failing, but it does not appear to time out completely! Here's the results I got on my local run:
> 
> ```
> Finished in 12 minutes 39 seconds (files took 5.48 seconds to load)
> 505 examples, 108 failures, 42 pending
> ```
> 
> Passing 80% of examples is good, right? 😀
> 
> Nearly all of the failures are this:
> 
> ```
>  81) Ferrum::Page::Screenshot#screenshot when encoding is base64 with jpeg supports screenshotting just the selected element
>       Failure/Error: raise NoSuchTargetError unless resolved
>       
>       Ferrum::NoSuchTargetError:
>         Ferrum::NoSuchTargetError
>       Shared Example Group: "screenshot screen" called from ./spec/page/screenshot_spec.rb:321
>       # ./lib/ferrum/context.rb:54:in 'create_target'
>       # ./lib/ferrum/context.rb:20:in 'default_target'
>       # ./lib/ferrum/context.rb:24:in 'page'
>       # ./spec/page/screenshot_spec.rb:38:in 'block in <main>'
> ```
> 
> It seems like something fails and is not recovered, and then it starts failing all of these specs because of that. Any thoughts on where to look?

Inside Ferrum we use lots of ruby concurrency primitives. They might be related to issue, it works well for cruby though.
Target is usually a page in chrome browser, so the error means for some reason target is closed or not found. My gut feeling is it’s all related to concurrency or IO.

**Comment by route** [comment]
Just for reference there was another attempt to make it work on jruby platform https://github.com/rubycdp/ferrum/pull/401

**Comment by sandstrom** [comment]
I would move this to discussions and gauge interest.

My understanding is that most people use cRuby/MRI, especially after the JIT-improvements in recent versions.

Also, ferrum as a tool should for many use-cases be I/O limited, and not CPU-limited, so it's not obvious how it would necessarily benefit from JRuby.

It would have been another matter if this was e.g. a high-performance async work queue.

**Comment by route** [comment]
If we have a JVM JRuby expert I would rather use his expertise because I think not so many things need to be fixed to make ferrum run on JRuby
