### ISSUE TITLE
Dialog also not working for me #176

### ISSUE THREAD

**Issue by jasonjei** [rubycdp/ferrum#183]
@route I'm having this issue as well

Reopening #176

bash-4.2# gem list | grep ferrum
ferrum (0.11) 

irb(main):006:0> browser.evaluate('navigator.userAgent.match(/(Ch
rome.*?)\s/)[1];');
=> "Chrome/86.0.4240.111"

Source html: https://tablesweep.s3.us-west-2.amazonaws.com/Braintree/test2.html
(will raise modal dialog when valid test credit card number entered)

**This version doesn't work--hangs when I display a modal dialog alert**
```
require 'ferrum'

browser = Ferrum::Browser.new(browser_options: { 'no-sandbox': nil, 'headless': nil, 'disable-gpu': nil, 'window-size': '1280x1696', 'disable-application-cache': nil, 'disable-infobars': nil, 'hide-scrollbars': nil, 'disable-dev-shm-usage': nil }, browser_path: '/var/task/bin/headless-chromium' )

browser.go_to("https://tablesweep.s3.us-west-2.amazonaws.com/Braintree/test2.html")

sleep 1.0

browser.frames[1].css('input')[0].focus.type('371736379851017')
browser.frames[2].css("input")[0].focus.type("1234")
browser.frames[3].css('input')[0].focus.type('112025')
browser.frames[4].css("input")[0].focus.type("94109", :Enter)

browser.css('input[type="submit"]')[0].click

sleep 1.0

browser.on(:dialog) do |dialog|
    dialog.dismiss
end

browser.screenshot(path: 'test.png')
```

bash-4.2# ruby test2.rb
Traceback (most recent call last):
        9: from test2.rb:22:in `<main>'
        8: from /var/lang/lib/ruby/2.7.0/forwardable.rb:235:in `css'
        7: from /var/lang/lib/ruby/2.7.0/forwardable.rb:235:in `css'
        6: from /var/runtime/gems/ferrum-0.11/lib/ferrum/frame/dom.rb:76:in `css'
        5: from /var/runtime/gems/ferrum-0.11/lib/ferrum/frame/runtime.rb:80:in `evaluate_func'
        4: from /var/runtime/gems/ferrum-0.11/lib/ferrum/frame/runtime.rb:124:in `call'
        3: from /var/runtime/gems/ferrum-0.11/lib/ferrum.rb:145:in `with_attempts'
        2: from /var/runtime/gems/ferrum-0.11/lib/ferrum/frame/runtime.rb:137:in `block in call'
        1: from /var/runtime/gems/ferrum-0.11/lib/ferrum/page.rb:160:in `command'
/var/runtime/gems/ferrum-0.11/lib/ferrum/browser/client.rb:46:in `command': Timed out waiting for response. It's possible that this happened because something took a very long time (for example a page load was slow). If so, setting the :timeout option to a higher value might help. (Ferrum::TimeoutError)

**It works once I take out the alert stuff.
Version that does work (goes to test.html)**

```
require 'ferrum'

browser = Ferrum::Browser.new(browser_options: { 'no-sandbox': nil, 'headless': nil, 'disable-gpu': nil, 'window-size': '1280x1696', 'disable-application-cache': nil, 'disable-infobars': nil, 'hide-scrollbars': nil, 'disable-dev-shm-usage': nil }, browser_path: '/var/task/bin/headless-chromium' )

browser.go_to("https://tablesweep.s3.us-west-2.amazonaws.com/Braintree/test.html")

sleep 1.0

browser.frames[1].css('input')[0].focus.type('371736379851017')
browser.frames[2].css("input")[0].focus.type("1234")
browser.frames[3].css('input')[0].focus.type('112025')
browser.frames[4].css("input")[0].focus.type("94109", :Enter)

browser.css('input[type="submit"]')[0].click

sleep 1.0

browser.on(:dialog) do |dialog|
    dialog.dismiss
end

browser.screenshot(path: 'test.png')

```

bash-4.2# ruby test.rb
Result is: tokencc_bc_c5q6vs_sg7zqv_5qpgwz_tb927m_f6z

__Originally posted by @jasonjei in https://github.com/rubycdp/ferrum/issues/176#issuecomment-866298776__

**Comment by route** [comment]
Could you please put this code
```
browser.on(:dialog) do |dialog|
    dialog.dismiss
end
```

straight after the code where the browser is instantiated `Ferrum::Browser.new` and tell us if it makes any difference

**Comment by jasonjei** [comment]
@route That seemed to have fixed the issue...

test2.rb
```
require 'ferrum'

browser = Ferrum::Browser.new(browser_options: { 'no-sandbox': nil, 'headless': nil, 'disable-gpu': nil, 'window-size': '1280x1696', 'disable-application-cache': nil, 'disable-infobars': nil, 'hide-scrollbars': nil, 'disable-dev-shm-usage': nil }, browser_path: '/var/task/bin/headless-chromium' )

browser.on(:dialog) do |dialog|
    dialog.dismiss
end

browser.go_to("https://tablesweep.s3.us-west-2.amazonaws.com/Braintree/test2.html")

retrycount = 0
while (not browser.frames.count > 4 or browser.frames[1].css("input").count == 0)  and retrycount != 5
        sleep 0.1
        retrycount += 1
end

browser.frames[1].css('input')[0].focus.type('371736379851017')
browser.frames[2].css("input")[0].focus.type("1234")
browser.frames[3].css('input')[0].focus.type('112025')
browser.frames[4].css("input")[0].focus.type("94109", :Enter)

browser.css('input[type="submit"]')[0].click

retrycount = 0
while browser.css("#result")[0].inner_text == "" and retrycount != 5
        sleep 0.1
        retrycount += 1
end

browser.on(:dialog) do |dialog|
    dialog.dismiss
end

puts "Result is: #{browser.css("#result")[0].inner_text}"
browser.screenshot(path: 'test.png')
```

Output:

```
bash-4.2# ruby test2.rb
Result is: tokencc_bc_7dtgky_48whmx_jgpq4g_p3kgcx_796
```

**Comment by route** [comment]
That's how it is. You declare a handler and this handler handles all dialogue messages. I can't think of the other way to do it and neither provides chrome
