### ISSUE TITLE
Screenshot of a screen portion.

### ISSUE THREAD

**Issue by mathieujobin** [rubycdp/ferrum#285]
I wish to be able to use ferrum to load a webpage and take a screenshot of a specific screen portion.

it should be delimited by x,y,w,h or css selector.

I tried....

```ruby
a = browser.position = { left: 80, top: 500 } ; browser.screenshot(path: "xe-test-1.jpg")
b = browser.screenshot(path: "xe-test-1.jpg", selector: "div#undefined")
c = browser.at_css("div#undefined").screenshot(path: "xe-test-1.jpg")
```

none works.

**Comment by zsan** [comment]
option `selector` is worked for me

```
 browser.screenshot(selector: "#CaptchaImage", path: "captcha.png")
 ```

**Comment by mathieujobin** [comment]
ok, how about this error...

```
2.7.6 :020 > browser.screenshot(path: "xe-test-2.jpg", selector: "dev section div div main div")
Traceback (most recent call last):
        31: from /home/mathieu/.rvm/gems/ruby-2.7.6/bin/ruby_executable_hooks:22:in `<main>'                         
        30: from /home/mathieu/.rvm/gems/ruby-2.7.6/bin/ruby_executable_hooks:22:in `eval'                        
        29: from /home/mathieu/.rvm/gems/ruby-2.7.6/bin/irb:23:in `<main>'                                        
        28: from /home/mathieu/.rvm/gems/ruby-2.7.6/bin/irb:23:in `load'                                          
        27: from /home/mathieu/.rvm/gems/ruby-2.7.6/gems/irb-1.4.1/exe/irb:11:in `<top (required)>'               
        10: from (irb):20:in `<main>'                                                                             
         9: from /home/mathieu/.rvm/rubies/ruby-2.7.6/lib/ruby/2.7.0/forwardable.rb:235:in `screenshot'           
         8: from /home/mathieu/.rvm/gems/ruby-2.7.6/gems/ferrum-0.11/lib/ferrum/page/screenshot.rb:33:in `screenshot'
         7: from /home/mathieu/.rvm/gems/ruby-2.7.6/gems/ferrum-0.11/lib/ferrum/page/screenshot.rb:143:in `screenshot_options'
         6: from /home/mathieu/.rvm/gems/ruby-2.7.6/gems/ferrum-0.11/lib/ferrum/page/screenshot.rb:159:in `get_bounding_rect'
         5: from /home/mathieu/.rvm/rubies/ruby-2.7.6/lib/ruby/2.7.0/forwardable.rb:235:in `evaluate_async'
         4: from /home/mathieu/.rvm/gems/ruby-2.7.6/gems/ferrum-0.11/lib/ferrum/frame/runtime.rb:70:in `evaluate_async'
         3: from /home/mathieu/.rvm/gems/ruby-2.7.6/gems/ferrum-0.11/lib/ferrum/frame/runtime.rb:124:in `call'
         2: from /home/mathieu/.rvm/gems/ruby-2.7.6/gems/ferrum-0.11/lib/ferrum.rb:145:in `with_attempts'
         1: from /home/mathieu/.rvm/gems/ruby-2.7.6/gems/ferrum-0.11/lib/ferrum/frame/runtime.rb:141:in `block in call'
/home/mathieu/.rvm/gems/ruby-2.7.6/gems/ferrum-0.11/lib/ferrum/frame/runtime.rb:157:in `handle_error': TypeError: Cannot read properties of null (reading 'getBoundingClientRect') (Ferrum::JavaScriptError)
    at <anonymous>:10:26
    at new Promise (<anonymous>)
    at <anonymous>:2:10
```

**Comment by ttilberg** [comment]
Might be a case of not-obvious error message. Are you sure that selector exists? Notably the first path, `dev` vs `div`?

**Comment by mathieujobin** [comment]
:man_facepalming: OMG.... so it works, but still need to scroll to that section...
![xe-test-2](https://user-images.githubusercontent.com/99191/189247493-fcbdbf07-3222-4216-b361-c0a626bfef27.jpg)

**Comment by route** [comment]
I think we could try to pass area arguments right to the method which now is not supported but can be

**Comment by zsan** [comment]
> I think we could try to pass area arguments right to the method which now is not supported but can be

That would be cool @route

**Comment by route** [comment]
@alexeyr-ci we just need to find either time for me or someone who can implement it ;)

**Comment by sandstrom** [comment]
I think this was fixed in https://github.com/rubycdp/ferrum/pull/410

Close?
