### ISSUE TITLE
`Emulation.setEmulatedMedia` not working?

### ISSUE THREAD

**Issue by gerjomarty** [rubycdp/ferrum#366]
Hello!

I'm trying to use the [Emulation.setEmulatedMedia](https://chromedevtools.github.io/devtools-protocol/tot/Emulation/#method-setEmulatedMedia) query to set the media query to `print`, but I get the error:

```
'Emulation.setEmulatedMedia' wasn't found (Ferrum::BrowserError)
```

Here is a single file reproduction of the problem:

```
require "bundler/inline"

gemfile do
  source "https://rubygems.org"
  gem "ferrum"
end

browser = Ferrum::Browser.new

browser.command("Emulation.setEmulatedMedia", media: "print")
browser.go_to("https://lachy.id.au/dev/css/tests/media/print/html401-print.html")
```

```
% ruby test.rb
/Users/me/.asdf/installs/ruby/3.1.4/lib/ruby/gems/3.1.0/gems/ferrum-0.13/lib/ferrum/browser/client.rb:97:in `raise_browser_error': 'Emulation.setEmulatedMedia' wasn't found (Ferrum::BrowserError)
	from /Users/me/.asdf/installs/ruby/3.1.4/lib/ruby/gems/3.1.0/gems/ferrum-0.13/lib/ferrum/browser/client.rb:49:in `command'
	from /Users/me/.asdf/installs/ruby/3.1.4/lib/ruby/gems/3.1.0/gems/ferrum-0.13/lib/ferrum/browser.rb:209:in `command'
	from test.rb:10:in `<main>'
```

I'm not entirely sure where the issue lies here, apologies if the root cause is actually somewhere down the line.

**Comment by ducharmemp** [comment]
This is an old issue but setEmulatedMedia appears to be a page-level command, not a browser command. To command the page you have to call `browser.page.command` instead. 

As an example for prefers-reduced-motion:
```ruby
browser.page.command('Emulation.setEmulatedMedia', features: [{name: 'prefers-reduced-motion', value: 'reduce'}])

```

**Comment by route** [comment]
Thanks for reporting, and thanks @ducharmemp for the correct diagnosis.

This isn't a bug in Ferrum — it's how CDP sessions/targets work. `Browser#command` sends to the browser-wide CDP connection, which only understands browser/target-scoped domains. Target-scoped domains like `Emulation`, `Page`, `DOM`, etc. have to go through a page's own session, i.e. `browser.page.command(...)` (or any `Page` instance's `#command`). All of Ferrum's internal `Emulation.*` calls already go through `Page` for this reason.

So the fix is simply:
```ruby
browser.page.command("Emulation.setEmulatedMedia", media: "print")
```

Closing as resolved — this was just missing documentation on the `browser.command` vs `page.command` distinction. Feel free to reopen if you hit something different.
