### ISSUE TITLE
Free up Chrome browser resources after page.go_to exceeds timeout

### ISSUE THREAD

**Issue by jschroeder** [rubycdp/ferrum#505]
If the CDP command `Page.navigate` in `Ferrum::Page#go_to` exceeds the timeout but no network traffic is pending, the application flow resumes. However, the browser instance seems to have a lingering connection hanging around.

Without the ability to clean up that connection a server can quickly run out of resources.

**To Reproduce**
```ruby
url = 'https://aberdeen.ecrash.interplat.com/'

15.times do |i|
  begin
    puts i
    browser = Ferrum::Browser.new
    browser.go_to url
  ensure
    browser.quit
  end
end
```

On a Google GCP VM at the 12th iteration the loop gets reliably aborted with error
```
...ferrum-0.16/lib/ferrum/page.rb:118:in `rescue in go_to': Request to https://aberdeen.ecrash.interplat.com/ reached server, but there are still pending connections: https://aberdeen.ecrash.interplat.com/ (Ferrum::PendingConnectionsError)
...ferrum-0.16/lib/ferrum/client.rb:92:in `send_message': Timed out waiting for response. It's possible that this happened because something took a very long time (for example a page load was slow). If so, setting the :timeout option to a higher value might help. (Ferrum::TimeoutError)
```
This problem does not exist if the page load finishes (e.g. url `https://google.com` instead of 'https://aberdeen.ecrash.interplat.com/').

Running the same example on a local (Mac) workstation, or on a Digital Ocean droplet didn't show the problem, but that might be because there is no such tight limit on "connection resources"??

**Expected behavior**
`browser.quit` should clean up resources so that it doesn't matter how often a new browser is instantiated in a short period of time.

The same problem exists if a single browser instance crates frequently new contexts.
Calling `page.close`, `page.stop`, `context.dispose` or `browser.crash` did not fix the problem.
Having a reliable way of closing out a browser session would be desirable.

**Comment by route** [comment]
Interesting worth investigating

**Comment by route** [comment]
# Investigation

I reproduced this on Linux and traced it. Summary up front: there are **two separate leaks** behind the "server runs
out of resources" symptom, one of which was already fixed on `main` after you filed this, and one of which was still
live and is now fixed. There is also a third, smaller one that Ferrum genuinely cannot fix, and I want to be explicit
about that rather than imply the problem is fully closed.

This turned out to be the same underlying bug as #364, and very probably the same as #315, so I've tied those
together below.

---

## 1. The error in the report is one exception, not two

Worth clearing up first, because it changes what we're looking for:

```
page.rb:118:in `rescue in go_to': ... (Ferrum::PendingConnectionsError)
client.rb:92:in `send_message': Timed out waiting for response ... (Ferrum::TimeoutError)
```

`Page#go_to` rescues `TimeoutError` and re-raises `PendingConnectionsError`, so Ruby is printing one exception plus
its `cause`. The loop aborts at iteration 12 simply because `Page.navigate` stopped returning in time by then.

That matters: the timeout is the **symptom**, not the leak. Iterations 0–11 exhausted something, and iteration 12 is
where the machine got slow enough for the navigation budget to blow. So the question isn't "why did `go_to` time
out", it's "what did the first eleven `quit`s fail to release".

## 2. Reproduction

`aberdeen.ecrash.interplat.com` isn't reachable for me, so I substituted a local TCP server that accepts the
connection, reads the request and never answers. That reproduces your exact failure shape — `Page.navigate` never
returns, `go_to` raises `PendingConnectionsError`, and the page is still mid-navigation when `quit` is called:

```ruby
server = TCPServer.new("127.0.0.1", 0)
held = []
Thread.new { loop { held << server.accept } }   # accept, never respond

N.times do
  b = Ferrum::Browser.new(timeout: 2, pending_connection_errors: true)
  begin
    b.go_to("http://127.0.0.1:#{server.addr[1]}/")
  rescue StandardError
    nil
  ensure
    b.quit
  end
end
```

On macOS this leaks nothing at all, which lines up with your "local Mac was fine". Everything below is Linux
(Docker, `ruby:3.3-slim`, Chromium 151, arm64).

## 3. First cause: `SIGUSR1` — already fixed on `main`, not yet released

You were on 0.16, where `Process.process_killer` sent **`SIGUSR1` to the leader pid only**. Chromium has no shutdown
handler for `USR1`, and the signal never reached the renderer/GPU/zygote children at all, since they weren't
signalled and the process group wasn't either.

c98c1ca (#616) replaced that with `TERM` → `KILL` to the whole process group, polling until the group is genuinely
empty, plus retrying user-data-dir removal instead of silently swallowing failures. That's on `main`, unreleased.

Being straight about the evidence: I could **not** get the old `USR1` path to leak with my synthetic hang — Chromium's
children noticed the dead IPC channel and exited on their own. So I can't claim that commit closes your case
specifically. It's clearly the right fix for the class of failure, but it isn't the one I can demonstrate.

## 4. Second cause: Ferrum never reaped Chrome's orphans — this one I can reproduce

This is the real one, and it's a bug that is still present on `main`.

Chrome is a process tree. Ferrum spawns the **browser** process (with `pgroup: true`); the renderer, GPU, zygote and
utility processes are children of *that*, i.e. Ferrum's **grandchildren**. When the browser process dies, they're
orphaned and reparented to PID 1, whose job is to `wait` on them. On a normal host that's systemd, and nobody ever
notices.

**In a container, your Ruby process usually *is* PID 1.** `CMD ["bundle", "exec", "ruby | puma | sidekiq"]` — there's no init. So
Chrome's orphans reparent to Ruby, and Ruby never reaps them. Measured, 6 browsers, Ruby as PID 1:

| | zombies after 6 × `Browser.new` + `go_to` + `quit` | wall clock |
|---|---|---|
| `main` before this fix | **42** (7 per `quit`, perfectly linear) | 30.96s |
| `main` + this fix | **0** | 19.03s |
| before the fix, but `docker run --init` | 0 | — |

```console
$ docker exec app ps -A
   34 ?  Z  [chromium] <defunct>
   35 ?  Z  [chromium] <defunct>
   55 ?  Z  [chromium] <defunct>
   ...
```

Each zombie holds a PID and a process-table slot. They're never reclaimed, so `fork` eventually starts failing and
everything — including Chrome startup and page loads — degrades. **That is a "server quickly runs out of resources"
that no amount of `page.close` / `context.dispose` / `browser.crash` can help with**, which is exactly what you
reported trying.

The `--init` row is the important control: with a real init in front, the identical unpatched code leaks nothing.
That isolates it to reaping, not to killing.

### The ~2 second bonus

Note the wall-clock column. This wasn't just a leak. `process_group_alive?` uses `kill(0, -pgid)` — and **a zombie
still answers signal 0**, because it's still in the process table. So the unreaped members kept the termination loop
believing the group was alive, and every single `quit` span until its 2-second `KILL_TIMEOUT` before giving up. In
this setup `quit` was paying ~2s of pure dead time per browser.

## 5. What Ferrum still can't clean up: `chrome_crashpad_handler`

Being honest about the residue. With the fix, 7 zombies per `quit` becomes 2, and the remaining two are always
`chrome_crashpad_handler`:

```
PID PPID PGID  SID STAT COMMAND
 22    1   21   21 Z    chrome_crashpad
 24    1   23   23 Z    chrome_crashpad
```

`PPID 1`, and `PGID`/`SID` of its own that match no live process — the classic double-fork daemonize. Chrome
**deliberately detaches** the crash handler into its own session, so it is never in the browser's process group and
never was Ferrum's child in any traceable way. It's an orphan of the container's init by design.

I checked whether it can simply be prevented from starting. It can't:

```
flags=[]                                                         crashpad_handlers=2
flags=[--disable-crash-reporter]                                 crashpad_handlers=2
flags=[--disable-crashpad-forwarding]                            crashpad_handlers=2
flags=[--noerrdialogs --disable-crash-reporter --disable-breakpad] crashpad_handlers=2
```

Ferrum already passes `--disable-breakpad` and `--disable-crash-reporter`; they stop it *reporting*, not *spawning*.

Ferrum could only reap these by calling `waitpid(-1)` — "reap anything" — which would steal the exit statuses of
child processes the host application spawned for its own reasons. A library must not do that. So: **an init in the
container is still required**, and I've documented that rather than pretend otherwise. The fix takes the tree Ferrum
owns down to zero; the self-daemonizing helper stays init's job.

## 6. What is *not* happening

Your hypothesis was "the browser instance seems to have a lingering connection hanging around". I chased that and it
doesn't hold at the socket level — after `quit`, the server side of the connection sees a clean FIN. No sockets, no fds, no temp dirs leak on current `main`.

## 7. Related issues — this is a recurring report

Cross-referencing, because this has come round several times and never had a code-level fix:

- **#364 "Leaking zombie processes"** — the same bug, filed 2023. Alpine image, `ruby app.rb` as PID 1, a loop of
  `Browser.new` + `quit`, 15 `[chrome] <defunct>`. It was closed the same day *by the reporter*, not by a fix, with
  "seems to be resolved by docker compose `init`".
- **#315 "Chrome processes not ending"** — Kubernetes, ferrum 0.13, screenshot workload. The detection command used there matches `[chrome] <defunct>` as well as live processes, so this is very plausibly the same leak. Worth noting for
  Kubernetes users specifically: there is no `init: true` in a pod spec, so tini has to be baked into the image —
  which is exactly the problem raised at the end of #364 and left unanswered.
- **rubycdp/cuprite#231** — a *different* failure of the same code path, with an excellent `/proc/PID/wchan`-backed
  root cause writeup. `Killer.kill` is installed as an `ObjectSpace` finalizer, and after escalating to `KILL` it
  did a **blocking, unbounded `Process.wait`**. Run during interpreter shutdown in a forked Rails parallel test
  worker, that hangs forever, and the parent then waits forever on a worker that never deregisters.

## One open question for you

Everything above assumes your app is containerized. You said "Google GCP VM" — if Ruby runs directly under systemd
there, orphans reparent to systemd, which reaps them, and the zombie path wouldn't be your root cause at all.

**Could you confirm whether that loop runs inside a container, and if so whether it has an init?**

The fix in work in progress now for what I could reproduce.

**Comment by growpath-jschroeder** [comment]
Thanks for the very thorough analysis and for spending so much time on this!

The app was **not** containerized at that time. The scenario ran in a fully functioning VM. The rails console ran in a shell, opened via ssh. I do remember seeing something about "crashpad" in the process list (a lot).

Unfortunately I don't have the VM available anymore. I containerized the app since then.
In the new setup there is a docker container for the rails app, a chrome container (ghcr.io/browserless/chromium) and the rails app accesses the chrome container via websocket on the internal docker network.

I just ran the loop in the rails container, and I can not reproduce the error, even while still running Ferrum 0.16.
**But**: The app still needs restarting every 3 weeks or so because the docker host comes to a grinding halt, running out of some resources. I have not been able to nail down what exactly happens there, I was assuming it was due to this "bug". 

I will try to replicate the problem again somehow....

Isn't it possible to create some kind of transaction that, when finishing, cleanly releases the chrome connection? Just to ensure no zombie processes and directories/resources stay around?

**Comment by route** [comment]
I'm going to land a few of fixes for this, one is: https://github.com/rubycdp/ferrum/pull/619

**Comment by jschroeder** [comment]
Additional info:

My production environment, where I have to restart the app every 3 weeks or so because of standstill, is still using Ferrum v0.16 and Chromium 131 in a separate docker container (ghcr.io/browserless/chromium).
Every day the list of `chrome` or `chrome_crashpad_handler` processes grows by a few of dozen. I can attach a sample of processes. May be you spot something.

I will upgrade everything as soon as I can replicate the problem in my test environment and verify improvements. Your changes to #619 look promising!

I am not able to replicate the problem of this bug report anymore, even with the old version of Ferrum. It might have been related to the old Chrome version??? Over the weekend I will switch our production server over to Ferrum v0.18 and the latest Chrome, and will watch the process list.

**Comment by jschroeder** [comment]
[process_list.txt](https://github.com/user-attachments/files/31566590/process_list.txt)

**Comment by route** [comment]
#619 is a dead end, the flag is corrupted for regular user and I believe internal chrome use only

**Comment by route** [comment]
@jschroeder if this is the list of processes for today, then I see nothing to reap or any leftovers of Chrome. All of these are six complete, live Chrome trees and still burning CPU. So this is not the reaping problem, not the init problem, and not the crashpad problem. Every browser has ppid=10 — browserless's node process. Ferrum never launched these browsers and cannot kill them — it only connects to browserless over a websocket. browserless spawns the Chrome and owns tearing it down when the session ends. It isn't doing that.

Upgrading Ferrum will not fix this. Worth checking, in order: browserless's TIMEOUT / CONNECTION_TIMEOUT setting (if it's -1, sessions never expire and a session that doesn't close cleanly lives forever), then the browserless version itself. Adding `browser.close` before `browser.quit` is cheap insurance and the right call for a remote browser regardless — it asks Chrome to exit instead of relying on browserless noticing a dropped socket.

**Comment by jschroeder** [comment]
No, this a are processes from August 12. They are still lingering. Every day I get 40-60 additional processes that hang around. Right now I have over 800 chrome processes hanging around. It is very good to know that this is a Chrome problem, not a Ferrum issue.

I am starting the Chrome container with TIMEOUT: 600000 (10 minutes max), and CONCURRENT: 20 (docs say default is 5, but default seems to be 10).

I will add `browser.close` before `browser.quit` and see if this all works.
Thank you so much!

**Comment by route** [comment]
Ok so for now I'm gonna close it as browserless adds it's own complexity. It seems to be not reaping problem either. Anyways on docker whether it's browserless or not, init is required. I'm gonna update docs about it https://docs.rubycdp.com/docs/ferrum/customization, it's already in main, but i need to regenerate. Anyways you can DM me and send sensitive info for investigation if problem still shows up

**Comment by route** [comment]
I think I have collected everything I could about leaks https://docs.rubycdp.com/docs/ferrum/docker there's no fix for ferrum code, it's all looking good. The problem is usually on the other side, in containers, browserless, environment.

**Comment by jschroeder** [comment]
Thank you. I'll start the container with option "init: true" and observe. I appreciate your deep dive into this and your explanation in the `Why this matters most in Docker` section.
